services:
  - type: web
    name: webmonitor-api
    runtime: python
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: GROQ_API_KEY
        sync: false
      - key: DB_PATH
        value: /temp/ebmonitor.db
